name: Push Weight-Loss-Trends to Shinyapps.io

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Cache apt packages
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: gdebi-core qpdf devscripts ghostscript
        version: 1.0
  
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-renv@v2
    
    - name: Set shinyapps.io credentials
      run: R -e 'rsconnect::setAccountInfo(name="cluffa", token="${{secrets.TOKEN}}", secret="${{secrets.SECRET}}")'
      
    - name: Deploy to shinyapps.io
      run: R -e 'rsconnect::deployApp(appDir = ".", forceUpdate = TRUE, launch.browser = FALSE)'